spec:
  template:
    spec:
      containers:
        -
          resources:
            requests:
              cpu: "0.2"
              memory: 256Mi
            limits:
              cpu: "1.0"
              memory: 256Mi
          env:
          - name: SPRING_APPLICATION_JSON
            value: '{"server":{"undertow":{"io-threads":1, "worker-threads":2 }}}'
          readinessProbe:
            failureThreshold: 3
            httpGet:
              #TODO change the readiness probe path to '/health'
              path: FIXME
              #TODO change the readiness probe port to 8182
              port: FIXME
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            failureThreshold: 3
            httpGet:
              #TODO change the liveness probe path to '/health'
              path: FIXME
              #TODO change the liveness probe port to 8182
              port: FIXME
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
